 name 			= "DCO Vehicle FSM"; // Name of your mod
 author 		= "YipMan (design), Deebs (design), Tally (code)"; // Affects Arma 3 Launcher, when the mod are loaded as local
 logo 			= "DCO_icon.jpg"; // Logo displayed in the main menu
 logoOver 		= "DCO_icon.jpg"; // When the mouse is over, in the main menu
 tooltip 		= "DCO Vehicle FSM";
 tooltipOwned 	= "credit_mod"; // Tool tip displayed when the mouse is left over, in the main menu
 picture 		= "DCO_Pic.jpg"; // Picture displayed from the expansions menu. Optimal size is 2048x1024
 actionName 	= "Discord";
 action 		= "https://discord.gg/bRTqWJzeza"; // Website URL, that can be accessed from the expansions menu
 overview 		= "DCO vehicle FSM introduces a AI system that dramatically increases vehicle survivability.<br/> This project has cost us well over 1k hours to build and refine, as well as personal investments and we are proud to finally be able to present it to the Arma-community!<br/><br/>Please show us your support by joining our community and giving us your valuable feedback, or join us in the further developement of ArmA 3 AI"; // Supports structured text
 hideName 		= 0; // Hide the extension name
 hidePicture	= 0;	// Hide the extension menu
 dlcColor[] 	= {0.23,0.39,0.30,1}; // Color used for DLC stripes and backgrounds (RGBA)
 logoSmall 		= "DCO_icon.jpg"; // Display in creative lists, next to the entities added by the mod